class Emoticons:
  def __init__(self):
    self.emoticons = None
  def get_emoticons(self):
    if not self.emoticons:
      self.emoticons = {
          "xx": "Love",
          "xxx": "Love",
          "xxxx": "Love",
          "xo":"Love",
          "xoxo":"Love",
          "xoxoxo":"Love",
          "xoxoxoxo":"Love",
          "x":"Love",
          "&lt;3": "Heart",
          "<3": "Heart",
          ":-)":"Smiley",
          ":)":"Smiley",
          "(:":"Smiley",
          ":o)":"Smiley",
          ":]":"Smiley",
          ":3":"Smiley",
          ":c)":"Smiley",
          ":>":"Smiley",
          "=]":"Smiley",
          "8)":"Smiley",
          "=)":"Smiley",
          ":}":"Smiley",
          ":^)":"Smiley",
          ":-D":"Happy",
          ":D":"Happy",
          "8-D":"Happy",
          "8D":"Happy",
          "x-D":"Happy",
          "xD":"Happy",
          "X-D":"Happy",
          "XD":"Happy",
          "=-D":"Happy",
          "=D":"Happy",
          "=-3":"Happy",
          "=3":"Happy",
          "B^D":"Happy",
          ":-))":"Happy",
          ">:[":"Frown",
          ":-(":"Frown",
          ":(":"Frown",
          ":-c":"Frown",
          ":c":"Frown",
          ":-<":"Frown",
          "":"Frown",
          ":<":"Frown",
          ":-[":"Frown",
          ":[":"Frown",
          ":{":"Frown",
          ":-||":"Frown",
          ":@":"Frown",
          ">:(":"Frown",
          ":'-(":"Crying",
          ":'(":"Crying",
          ":'-)":"Crying",
          ":')":"Crying",
          "D:<": "Sad",
          "D:": "Sad",
          "D8": "Sad",
          "D;": "Sad",
          "D=": "Sad",
          "DX": "Sad",
          "v.v": "Sad",
          "D-':": "Sad",
          ">:O": "Surprise",
          ":-O": "Surprise",
          ":O": "Surprise",
          ":O": "Surprise",
          "o_O": "Surprise",
          "o_0": "Surprise",
          "o.O": "Surprise",
          "8-0": "Surprise",
          ";-)": "Wink",
          ";)": "Wink",
          "*-)": "Wink",
          "*)": "Wink",
          ";-]": "Wink",
          ";]": "Wink",
          ";D": "Wink",
          ";^)": "Wink",
          ":-,": "Wink",
          ">:P": "Tongue",
          ":-P": "Tongue",
          ":P": "Tongue",
          "X-P": "Tongue",
          "x-p": "Tongue",
          "xp": "Tongue",
          "XP": "Tongue",
          ":-p": "Tongue",
          ":p": "Tongue",
          "=p": "Tongue",
          ":-b": "Tongue",
          ":b": "Tongue",
          ">:\\": "Skeptical",
          ">://": "Skeptical",
          ":-/": "Skeptical",
          ":-.": "Skeptical",
          ":/": "Skeptical",
          ":\\": "Skeptical",
          "=/": "Skeptical",
          "=\\": "Skeptical",
          ":L": "Skeptical",
          "=L": "Skeptical",
          ":S": "Skeptical",
          ">.<": "Skeptical",
          ":|": "StraightFace",
          ":-|":"StraightFace",
          ":-X": "Braces",
          ":X": "Braces",
          ":-#": "Braces",
          ":#": "Braces",
          "O:-)": "Angel",
          "0:-3": "Angel",
          "0:3": "Angel",
          "0:-)": "Angel",
          "0:)": "Angel",
          "0;^)": "Angel",
          ">:)": "Evil",
          ">;)": "Evil",
          ">:-)": "Evil",
          "}:-)": "Evil",
          "}:)": "Evil",
          "3:-)": "Evil",
          "3:)": "Evil",
          "o/\o": "HighFive",
          "^5": "HighFive",
          ">_>^": "HighFive",
          "^<_<": "HighFive",
          "|;-)": "Bored",
          "|-O": "Bored",
          ":-&": "Tongue",
          ":&": "Tongue",
          "#-)": "Drunk", 
          "%-)": "Drunk",
          "%)": "Drunk",
          ":-###..": "Drunk",
          ":###..": "Drunk",
          "<:-|": "Dumb",
          "&amp;": "AMPERSAND",
          "&gt;": "GREATERTHAN",
          "&lt;": "LESSTHAN"}
    return self.emoticons
